

# =========================================================
# APPLICATION
# =========================================================

spring.application.name=quantity-measurement-app
app.security.public-paths=/api/auth/**,/swagger-ui/**,/swagger-ui.html,/v3/api-docs/**,/actuator/health,/h2-console/**

# =========================================================
# SERVER CONFIGURATION
# =========================================================

server.port=8080

# =========================================================
# ACTIVE PROFILE
# =========================================================

spring.profiles.active=dev

# =========================================================
# H2 DATABASE CONFIGURATION
# =========================================================

spring.datasource.url=jdbc:h2:mem:quantitydb;DB_CLOSE_DELAY=-1

spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=sa

spring.datasource.password=

# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# =========================================================
# H2 CONSOLE
# =========================================================

spring.h2.console.enabled=true

spring.h2.console.path=/h2-console

# =========================================================
# ACTUATOR
# =========================================================


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# =========================================================
# LOGGING
# =========================================================

logging.level.root=INFO

logging.level.com.quantity.measurement=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# =========================================================
# GOOGLE OAUTH2
# =========================================================


#spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

#spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.client-id=762091255963-5gohnueo57dhfu61o7e106fpd74vsa4c.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=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



spring.security.oauth2.client.registration.google.scope=openid,email,profile

# =========================================================
# JWT CONFIGURATION
# =========================================================
#app.jwt.secret=${JWT_SECRET}
app.jwt.secret=ThisIsAVerySecretKeyForJwtTokenGeneration123456789

app.jwt.expiration=86400000

# =========================================================
# SWAGGER
# =========================================================

springdoc.swagger-ui.path=/swagger-ui.html